name: Test Backend

on:
  push:
    branches:
      - main
    paths:
      - 'sipenamas_v2_backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'sipenamas_v2_backend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sipenamas_v2_backend

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        coverage: none

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Generate Key
      run: php artisan key:generate

    - name: Run Tests
      run: php artisan test --compact
